apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: igtt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: igtt
    app.kubernetes.io/part-of: byoc-app-gdbz
  name: igtt
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: igtt
status:
  loadBalancer: {}
