apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: igtt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: igtt
    app.kubernetes.io/part-of: byoc-app-gdbz
  name: igtt
spec:
  rules:
  - host: igtt-byoc-wzgy-tenant.apps.caafeddff6111bc42205.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: igtt
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
